language: java

# safelist
branches:
  only:
  - master

jdk:
  - openjdk8
  
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_deploy:
   zip $COMMIT-transfer target/dw*.jar config.yml Procfile
   
deploy:
   provider: elasticbeanstalk
   app: "dw-os-test"
   env: "dw-os-test-dev"
   access_key_id: $AWS_KEY
   secret_access_key: $AWS_SECRET
   region: "eu-west-1"
   zip_file: $COMMIT-transfer.zip
   bucket_name: "elasticbeanstalk-eu-west-1-601912882130"
   skip_cleanup: "true"
   on:
        branch: "master"   
