logging:
  level: INFO
  loggers:
    ch.dulce: DEBUG

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 5000

database:
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: ${DB_USER:-root}

  # the password
  password: ${DB_PASSWORD:-my-secret-pw}

  # the JDBC URL
  url: ${DB_URL:-jdbc:mysql://localhost:3306/awsdb}
